/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsRespirationRouteImport } from './routes/reports.respiration'
import { Route as ReportsMicroscopeRouteImport } from './routes/reports.microscope'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRespirationRoute = ReportsRespirationRouteImport.update({
  id: '/reports/respiration',
  path: '/reports/respiration',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsMicroscopeRoute = ReportsMicroscopeRouteImport.update({
  id: '/reports/microscope',
  path: '/reports/microscope',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reports/microscope': typeof ReportsMicroscopeRoute
  '/reports/respiration': typeof ReportsRespirationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reports/microscope': typeof ReportsMicroscopeRoute
  '/reports/respiration': typeof ReportsRespirationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reports/microscope': typeof ReportsMicroscopeRoute
  '/reports/respiration': typeof ReportsRespirationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reports/microscope' | '/reports/respiration'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reports/microscope' | '/reports/respiration'
  id: '__root__' | '/' | '/reports/microscope' | '/reports/respiration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportsMicroscopeRoute: typeof ReportsMicroscopeRoute
  ReportsRespirationRoute: typeof ReportsRespirationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/respiration': {
      id: '/reports/respiration'
      path: '/reports/respiration'
      fullPath: '/reports/respiration'
      preLoaderRoute: typeof ReportsRespirationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/microscope': {
      id: '/reports/microscope'
      path: '/reports/microscope'
      fullPath: '/reports/microscope'
      preLoaderRoute: typeof ReportsMicroscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportsMicroscopeRoute: ReportsMicroscopeRoute,
  ReportsRespirationRoute: ReportsRespirationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
